/**
 * Created by liu on 15/12/8.
 */
 module.exports = [
 {
  namezh:'土地利用相关数据',
  fields:[
  {
    namezh:'建设用地集约性',
    fields:[
    {
      namezh:'镇域人均建设用地面积',
      calinfo:'A1/A30',
      reference:'绿色低碳重点小城镇建设评价指标（试行）',
      type:'value',
      unit:'㎡/人',
      sign:'Z4'
    },
    {
      namezh:'各村镇人均建设用地面积',
      calinfo:'B1/A30、C17/A30',
      reference:'严寒地区绿色村镇体系指标体系',
      type:'table',
      unit:'㎡/人',
      sign:'Z5'
    },
    ]
  },
  {
    namezh:'生态容量指数',
    fields:[
    {
      namezh:'镇域生态容量指标',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z6'
    },

    ],
  },
  {
    namezh:'可达性指数',
    fields:[
    {
      namezh:'镇域交通设施密度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z11'
    },

    ],
  },
  {
    namezh:'耕地资源指数',
    fields:[
    {
      namezh:'人均耕地面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z13'
    },
    {
      namezh:'年平均变化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z14'
    },
    {
      namezh:'各村镇人均耕地面积',
      calinfo:'',
      reference:'',
      type:'table',
      unit:'',
      sign:'Z15'
    },
    ],
  },
  ]
},
{
  namezh:'居民点系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'居民对地区福利保障条件满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z20'
    },
    {
      namezh:'镇区绿化覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z21'
    },
    {
      namezh:'村镇人口密度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z23'
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'人均收入',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z26'
    },
    {
      namezh:'村庄人均建设用地面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z30'
    },
    {
      namezh:'镇区与村庄人均收入比值',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z32'
    },
    {
      namezh:'镇区人均建设用地面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z34'
    },
    ],
  },
  {
    namezh:'社会和谐进步',
    fields:[
    {
      namezh:'城镇化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z36'
    },
    {
      namezh:'人口10年间平均变化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z38'
    },
    ],
  },
  ],
},
{
  namezh:'产业生产系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'化肥施用强度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z43'
    },
    {
      namezh:'农产品剩余物综合利用率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z45'
    },
    {
      namezh:'绿色无公害农产品种植面积比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z46'
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'农田综合生产率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z48'
    },
    {
      namezh:'农业劳作平均出行距离',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z54'
    },
    {
      namezh:'二三产业GDP贡献率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z55'
    },
    {
      namezh:'人均农业劳动生产力',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z56'
    },
    {
      namezh:'二、三产业从业人员比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z58'
    },
    ],
  },
  ],
},
{
  namezh:'能耗与基础设施系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'建成区生活污水处理率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z63'
    },
    {
      namezh:'木柴、秸秆在取暖燃料中的比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z64'
    },

    {
      namezh:'生活用水满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z66'
    },
    {
      namezh:'垃圾收集设施覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z67'
    },
    {
      namezh:'居民绿色出行方式比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z68'
    },

    {
      namezh:'居民生活污水无害化处理率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z70'
    },

    {
      namezh:'居民户均取暖能源消耗量',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z72'
    },
    {
      namezh:'自来水普及率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z73'
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'人均道路网密度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z74'
    },
    {
      namezh:'户均用电量',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z76'
    },
    {
      namezh:'村镇道路硬化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z77'
    },
    {
      namezh:'道路交通设施满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z79'
    },
    ],
  },
  ],
},
{
  namezh:'公共设施系统',
  fields:[
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'中学生均学校建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z84'
    },
    {
      namezh:'小学生均学校建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z86'
    },
    ],
  },
  {
    namezh:'社会和谐进步',
    fields:[
    {
      namezh:'教育公共设施服务满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z88'
    },
    {
      namezh:'医疗公共设施服务满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z89'
    },
    {
      namezh:'人均卫生设施建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z90'
    },

    {
      namezh:'公共设施用地比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z92'
    },

    {
      namezh:'卫生设施千人病床数',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z94'
    },
    ],
  },
  ],
},
{
  namezh:'气候与生态环境相关数据',
  fields:[
  {
    namezh:'水土保持指数',
    fields:[
    {
      namezh:'水土保持能力',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z99'
    },
    ],
  },
  {
    namezh:'生态脆弱指数',
    fields:[
    {
      namezh:'地形起伏度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z102'
    },
    {
      namezh:'灾害易发度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z105'
    },
    ],
  },
  {
    namezh:'自然保护指数',
    fields:[
    {
      namezh:'自然保护区面积比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z107'
    },

    ],
  },
  {
    namezh:'气候资源指数',
    fields:[
    {
      namezh:'年平均降水',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z109'
    },
    {
      namezh:'年均无霜期',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z110'
    },
    ],
  },
  {
    namezh:'生态健康指数',
    fields:[
    {
      namezh:'森林覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z111'
    },
    {
      namezh:'本地木本植物指数',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z113'
    },
    ],
  },
  ],
},
]