/**
 * Created by liu on 15/12/8.
 */
 module.exports = [
  {
  namezh:'土地利用相关数据',
  fields:[
  {
    namezh:'建设用地集约性',
    fields:[
    {
      namezh:'镇域人均建设用地面积',
      calinfo:'A1/A30',
      reference:'绿色低碳重点小城镇建设评价指标（试行）',
      type:'value',
      unit:'㎡/人',
      sign:'Z4',
      score:{
        judge:{
          'M>=140':0,
          'M>=120':0.5,
          'def':1,
        },
      }
    },
    //{
    //  namezh:'各村镇人均建设用地面积',
    //  calinfo:'B1/A30、C17/A30',
    //  reference:'严寒地区绿色村镇体系指标体系',
    //  type:'table',
    //  unit:'㎡/人',
    //  sign:'Z5'
    //},
    ]
  },
  {
    namezh:'生态容量指数',
    fields:[
    {
      namezh:'镇域生态容量指标',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z6',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
        comment:'所有乡镇均值',
      }
    },
    ],
  },
  {
    namezh:'可达性指数',
    fields:[
    {
      namezh:'镇域交通设施密度',
      calinfo:'',
      reference:'所有乡镇均值',
      type:'value',
      unit:'',
      sign:'Z11',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
        comment:'所有乡镇均值',
      }
    },

    ],
  },
  {
    namezh:'耕地资源指数',
    fields:[
    {
      namezh:'人均耕地面积',
      calinfo:'',
      reference:'所有乡镇均值',
      type:'value',
      unit:'',
      sign:'Z13',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
        comment:'所有乡镇均值',
      }
    },
    {
      namezh:'年平均变化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z14',
      score:{
        judge:{
          'Math.abs(M)>=0.05':0,
          'Math.abs(M)>=0.03':0.5,
          'def':1,
        },
        comment:'所有乡镇均值',
      }
    },
    //{
    //  namezh:'各村镇人均耕地面积',
    //  calinfo:'',
    //  reference:'',
    //  type:'table',
    //  unit:'',
    //  sign:'Z15'
    //},
    ],
  },
  ]
},
  {
  namezh:'居民点系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'居民对地区福利保障条件满意度',
      calinfo:'根据问卷"很不满意"至"满意"（0、25、50、75、100）平均得分',
      reference:'',
      type:'value',
      unit:'%',
      sign:'Z20',
      score:{
        judge:{
          'M>=0.95':1,
          'def':'(M-Min)/(0.95-Min)',
        },
        comment:'所有乡镇均值',
      }
    },
    {
      namezh:'镇区绿化覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'%',
      sign:'Z21',
      score:{
        judge:{
          'M>=0.12':1,
          'def':'(M-Min)/(0.12-Min)',
        },
        comment:'',
      }
    },
    {
      namezh:'村镇人口密度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z23'
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'人均收入',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z26',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
        comment:'所有乡镇均值',
      }
    },
    {
      namezh:'村庄人均建设用地面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z30',
      score:{
        judge:{
          'M<=80':1,
          'def':'(Max-M)/(Max-80)',
        },
        comment:'',
      }
    },
    {
      namezh:'镇区与村庄人均收入比值',
      calinfo:'',
      reference:'所有乡镇均值',
      type:'value',
      unit:'',
      sign:'Z32',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
        comment:'',
      }
    },
    {
      namezh:'镇区人均建设用地面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z34',
      score:{
        judge:{
          'M<=100':1,
          'def':'(Max-M)/(Max-100)',
        },
        comment:'',
      }
    },
    ],
  },
  {
    namezh:'社会和谐进步',
    fields:[
    {
      namezh:'城镇化率',
      calinfo:'',
      reference:'所有乡镇均值',
      type:'value',
      unit:'',
      sign:'Z36',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
      }
    },
    {
      namezh:'人口10年间平均变化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z38'
    },
    ],
  },
  ],
},
  {
  namezh:'产业生产系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'化肥施用强度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'公斤/公顷',
      sign:'Z43',
      score:{
        judge:{
          'M<=250':1,
          'def':'(Max-M)/(Max-250)',
        },
      }
    },
    {
      namezh:'农产品剩余物综合利用率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z45',
      score:{
        judge:{
          'M>=0.90':1,
          'def':'(M-Min)/(0.90-Min)',
        },
      }
    },
    {
      namezh:'绿色无公害农产品种植面积比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z46',
      score:{
        judge:{
          'M>=0.60':1,
          'def':'(M-Min)/(0.60-Min)',
        },
      }
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'农田综合生产率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z48',
      score:{
        judge:{
          'M<=3500':1,
          'def':'(Max-M)/(Max-3500)',
        },
      }
    },
    {
      namezh:'农业劳作平均出行距离',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z54',
      score:{
        judge:{
          'M<=250':1,
          'def':'(Max-M)/(Max-250)',
        },
      }
    },
    {
      namezh:'二三产业GDP贡献率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z55',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    {
      namezh:'人均农业劳动生产力',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z56',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    {
      namezh:'二、三产业从业人员比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z58',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    ],
  },
  ],
},
  {
  namezh:'能耗与基础设施系统',
  fields:[
  {
    namezh:'生态环境健康',
    fields:[
    {
      namezh:'建成区生活污水处理率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z63',
      score:{
        judge:{
          'M>=0.80':1,
          'def':'(M-Min)/(0.80-Min)',
        },
      }
    },
    {
      namezh:'木柴、秸秆在取暖燃料中的比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z64',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
      }
    },

    {
      namezh:'生活用水满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z66',
      score:{
        judge:{
          'def':'(M-Min)/(1-Min)',
        },
      }
    },
    {
      namezh:'垃圾收集设施覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z67',
      score:{
        judge:{
          'def':'(M-Min)/(1-Min)',
        },
      }
    },
    {
      namezh:'居民绿色出行方式比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z68',
      score:{
        judge:{
          'M<=250':1,
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },

    {
      namezh:'居民生活污水无害化处理率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z70',
      score:{
        judge:{
          'M>=0.70':1,
          'def':'(M-Min)/(0.70-Min)',
        },
      }
    },

    {
      namezh:'居民户均取暖能源消耗量',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z72',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
      }
    },
    {
      namezh:'自来水普及率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z73',
      score:{
        judge:{
          'M>=0.90':1,
          'def':'(M-Min)/(0.90-Min)',
        },
      }
    },
    ],
  },
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'人均道路网密度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'公里/平方公里*人',
      sign:'Z74',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
      }
    },
    {
      namezh:'户均用电量',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'KWH',
      sign:'Z76',
      score:{
        judge:{
          'def':'(Max-M)/(Max-Min)',
        },
      }
    },
    {
      namezh:'村镇道路硬化率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'%',
      sign:'Z77',
      score:{
        judge:{
          'M>=0.95':1,
          'def':'(M-Min)/(0.95-Min)',
        },
      }
    },
    {
      namezh:'道路交通设施满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z79',
      score:{
        judge:{
          'M>=0.95':1,
          'def':'(M-Min)/(0.95-Min)',
        },
      }
    },
    ],
  },
  ],
},
  {
  namezh:'公共设施系统',
  fields:[
  {
    namezh:'经济发展持续',
    fields:[
    {
      namezh:'中学生均学校建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'平方米/学生',
      sign:'Z84',
      score:{
        judge:{
          'M>=5.6 && M<=10.1':1,
          'M<5.6':'(M-Min)/(5.6-Min)',
          'def':'(Max-M)/(Max-10.1)'
        },
      }
    },
    {
      namezh:'小学生均学校建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'平方米/学生',
      sign:'Z86',
      score:{
        judge:{
          'M>=5.6 && M<=10.1':1,
          'M<5.6':'(M-Min)/(5.6-Min)',
          'def':'(Max-M)/(Max-10.1)'
        },
      }
    },
    ],
  },
  {
    namezh:'社会和谐进步',
    fields:[
    {
      namezh:'教育公共设施服务满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z88',
      score:{
        judge:{
          'M>=0.95':1,
          'def':'(M-Min)/(0.95-Min)',
        },
      }
    },
    {
      namezh:'医疗公共设施服务满意度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z89',
      score:{
        judge:{
          'M>=0.95':1,
          'def':'(M-Min)/(0.95-Min)',
        },
      }
    },
    {
      namezh:'人均卫生设施建筑面积',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'平方米/人',
      sign:'Z90',
      score:{
        judge:{
          'M>=0.08 && M<=0.1':1,
          'M<0.08':'(M-Min)/(0.08-Min)',
          'def':'(Max-M)/(Max-0.1)'
        },
      }
    },

    {
      namezh:'公共设施用地比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z92',
      score:{
        judge:{
          'M>=12':1,
          'def':'(M-Min)/(12-Min)',
        },
      }
    },

    {
      namezh:'卫生设施千人病床数',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z94',
      score:{
        judge:{
          'M>=1.6':1,
          'def':'(M-Min)/(1.6-Min)',
        },
      }
    },
    ],
  },
  ],
},
  {
  namezh:'气候与生态环境相关数据',
  fields:[
  {
    namezh:'水土保持指数',
    fields:[
    {
      namezh:'水土保持能力',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z99',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      },
      visible:false,
    },
    ],
  },
  {
    namezh:'生态脆弱指数',
    fields:[
    {
      namezh:'地形起伏度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z102',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    {
      namezh:'灾害易发度',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z105',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    ],
  },
  {
    namezh:'自然保护指数',
    fields:[
    {
      namezh:'自然保护区面积比例',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z107',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },

    ],
  },
  {
    namezh:'气候资源指数',
    fields:[
    {
      namezh:'年平均降水',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z109',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    {
      namezh:'年均无霜期',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z110',
      score:{
        judge:{
          'def':'(M-Min)/(Max-Min)',
        },
      }
    },
    ],
  },
  {
    namezh:'生态健康指数',
    fields:[
    {
      namezh:'森林覆盖率',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z111',
      score:{
        judge:{
          '0.75<=M':1,
          'M<0.18':0,
          'def':'(M-0.18)/0.57',
        },
      }
    },
    {
      namezh:'本地木本植物指数',
      calinfo:'',
      reference:'',
      type:'value',
      unit:'',
      sign:'Z113',
      score:{
        judge:{
          '0.9<=M':1,
          'M<0.7':0,
          'def':'(M-0.7)/0.002',
        },
      }
    },
    ],
  },
  ],
},
]